name: Beginner GitHub Actions Demo

on: 
  push:
    branches: [ main ]

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      - name: Step 2 - Print Hello
        run: echo "Hello from GitHub Actions!"

      - name: Step 3 - Run multiple commands
        run: |
          echo "This is your first workflow."
          echo "You are learning GitHub Actions step by step."
