name: Second Workflow

on: push

jobs:
  demo-job1:
    runs-on: ubuntu-latest 

    steps:
     - name: check out code
       uses: actions/checkout@v4

     - name: Print message
       run: echo "hello sohail bagali" 
